package com.skillstorm.reliable_api.dtos;

import java.math.BigDecimal;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

/**
 * Data Transfer Object (DTO) for representing product master data.
 * This class is used for data exchange, particularly during the creation, retrieval,
 * and listing of product entities. It includes fields for core product attributes,
 * pricing, and regulatory flags (hazardous, expiration required).
 *
 * @author Jevaughn Stewart
 * @version 1.0
 */
public class ProductDTO {
    
    /**
     * The name of the product. Must not be blank and has a maximum size of 200 characters.
     */
    @Size(max = 200)
    @NotBlank 
    private String name;
    
    /**
     * The Stock Keeping Unit (SKU) of the product. Must be unique across all products
     * and not be blank. Has a maximum size of 100 characters.
     */
    @Size(max = 100)
    @NotBlank
    private String sku;
    
    /**
     * A detailed description of the product.
     */
    private String description;
    
    /**
     * The public, universally unique identifier (UUID or similar) for the product.
     * This is generated by the system and used for external lookups.
     */
    private String publicId;
    
    /**
     * The foreign key ID linking to the product's {@code Category}.
     */
    private Long categoryId;
    
    /**
     * The unit of measure for this product (e.g., 'box', 'kilogram', 'each').
     */
    private String unit;
    
    /**
     * Flag indicating if the product is classified as a hazardous material.
     */
    private Boolean isHazardous;
    
    /**
     * Flag indicating if individual inventory batches of this product must track an expiration date.
     */
    private Boolean expirationRequired;
    
    /**
     * The selling price of the product. Must not be null.
     */
    @NotNull
    private BigDecimal price;
    
    // Getters and Setters

    /**
     * Provides accessor and mutator methods for all product fields:
     * (name, sku, description, publicId, categoryId, unit, isHazardous, expirationRequired, price).
     * <p>
     * {@code getName()}, {@code setName(String name)}
     * <p>
     * {@code getSku()}, {@code setSku(String sku)}
     * <p>
     * {@code getDescription()}, {@code setDescription(String description)}
     * <p>
     * {@code getPublicId()}, {@code setPublicId(String publicId)}
     * <p>
     * {@code getCategoryId()}, {@code setCategoryId(Long categoryId)}
     * <p>
     * {@code getUnit()}, {@code setUnit(String unit)}
     * <p>
     * {@code getIsHazardous()}, {@code setIsHazardous(Boolean isHazardous)}
     * <p>
     * {@code getExpirationRequired()}, {@code setExpirationRequired(Boolean expirationRequired)}
     * <p>
     * {@code getPrice()}, {@code setPrice(BigDecimal price)}
     * </p>
     */
    public BigDecimal getPrice() {
        return price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public String getSku() {
        return sku;
    }
    
    public void setSku(String sku) {
        this.sku = sku;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getPublicId() {
        return publicId;
    }
    
    public void setPublicId(String publicId) {
        this.publicId = publicId;
    }
    
    public Long getCategoryId() {
        return categoryId;
    }
    
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }
    
    public String getUnit() {
        return unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    
    public Boolean getIsHazardous() {
        return isHazardous;
    }
    
    public void setIsHazardous(Boolean isHazardous) {
        this.isHazardous = isHazardous;
    }
    
    public Boolean getExpirationRequired() {
        return expirationRequired;
    }
    
    public void setExpirationRequired(Boolean expirationRequired) {
        this.expirationRequired = expirationRequired;
    }
}